### PR TITLE
Adding climate control functions

### PR DESCRIPTION
**Pull request by ye0534143454**
Full control of climate control
Options
**16:30>TO** turn on
**16:30>TMC** = set mode cool, option H\D\A\F
**16:30>TT22.5** = set temperature, option 22.5\22
**16:30>TP3** = set  power fan high, option A\1\2\3
**16:30>TS0** = swing off, option 0 = off \ 1 = vertical \ 2 = horizontal \ 3 =both
You can change everything separately and you can combine together whatever you want,
 for example **16:30>T_MC_T22.5_P3_S2**
or  **16:30>TO_PA_T22**

צילום מסך 2024-10-09 023527
צילום מסך 2024-10-10 023119

I'm a really beginner programmer, I'd love to hear what needs to be improved
Thanks for the amazing project

### CODE REVIEW

**Comment by htht2001** [comment]
@arthurdent75
Is there a merger expected?

**Comment by arthurdent75** [comment]
Sorry, I don't think it will be merged. I'm not fully into this choice.
I appreciate your interest.

**Comment by ye0534143454** [comment]
Are you referring to a syntax change that would look something like this?
16:30>{TO, TMC, T22.5, P3, S2}
Or are you suggesting the use of external scripts?

**Comment by arthurdent75** [comment]
> Are you referring to a syntax change that would look something like this? 16:30>{TO, TMC, T22.5, P3, S2} Or are you suggesting the use of external scripts?

Both.
You choose to execute a script.
As an option, you can choose to send one or more parameters to the script.
So, in your case, you can create a script to start the climate, and this script can accept any parameter you like, in the syntax that you like.

E.g. (for simplicity with temperature and mode only - generated with ChatGPT)

```
script:
  set_climate:
    description: >
      Set a climate device with the specified entity, temperature, and mode.
      Parameters:
        - entity_id: The entity ID of the climate device.
        - temperature: The desired temperature.
        - mode: The desired mode (H=Hot, C=Cold, D=Dry, A=Auto, F=Fan).
    fields:
      entity_id:
        description: The climate entity to control.
        example: climate.living_room
        required: true
      temperature:
        description: The target temperature to set.
        example: 22
        required: true
      mode:
        description: The mode to set (H, C, D, A, F).
        example: H
        required: true
    sequence:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ mode | upper == 'H' }}"
            sequence:
              - service: climate.set_hvac_mode
                target:
                  entity_id: "{{ entity_id }}"
                data:
                  hvac_mode: heat
          - conditions:
              - condition: template
                value_template: "{{ mode | upper == 'C' }}"
            sequence:
              - service: climate.set_hvac_mode
                target:
                  entity_id: "{{ entity_id }}"
                data:
                  hvac_mode: cool
          - conditions:
              - condition: template
                value_template: "{{ mode | upper == 'D' }}"
            sequence:
              - service: climate.set_hvac_mode
                target:
                  entity_id: "{{ entity_id }}"
                data:
                  hvac_mode: dry
          - conditions:
              - condition: template
                value_template: "{{ mode | upper == 'A' }}"
            sequence:
              - service: climate.set_hvac_mode
                target:
                  entity_id: "{{ entity_id }}"
                data:
                  hvac_mode: auto
          - conditions:
              - condition: template
                value_template: "{{ mode | upper == 'F' }}"
            sequence:
              - service: climate.set_hvac_mode
                target:
                  entity_id: "{{ entity_id }}"
                data:
                  hvac_mode: fan_only
        default:
          - raise: "Invalid mode provided. Use H, C, D, A, or F."
      - service: climate.set_temperature
        target:
          entity_id: "{{ entity_id }}"
        data:
          temperature: "{{ temperature }}"
```

Then you select _script.set_climate_ as entity in the scheduler and you will write:
**16:30>{"climate.myclimate","22.5","C"}**

**Comment by Code394** [comment]
Thank you.
However, if I choose a script as an entity, it's difficult to conveniently determine which schedule belongs to each entity. Is there another solution that would allow using this style:
16:30>{TO, TMC, T22.5, P3, S2}
That you can choose the climate as an entity

**Comment by arthurdent75** [comment]
> it's difficult to conveniently determine which schedule belongs to each entity

set the name of the scheduler accordingly

**Comment by Code394** [comment]
Perhaps consider adding an optional setting for 'Extended Climate Control' that would provide users who desire it with full control over climate settings from this scheduler.
The current script-based approach is still not very user-friendly

**Pull request closed without merging**
